//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wmsMLC.RCL.Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wmsMLC.RCL.Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использование: {0} [Server]{1}[Server - наименование TS]{1}[? - это окно].
        /// </summary>
        internal static string AppParametersInfo {
            get {
                return ResourceManager.GetString("AppParametersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимое наименование ТСД &apos;{0}&apos;.{1}{2}.
        /// </summary>
        internal static string BadComputerName {
            get {
                return ResourceManager.GetString("BadComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string ComputerName {
            get {
                return ResourceManager.GetString("ComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домен.
        /// </summary>
        internal static string DomainName {
            get {
                return ResourceManager.GetString("DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка..
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение будет закрыто..
        /// </summary>
        internal static string FatalErrorExit {
            get {
                return ResourceManager.GetString("FatalErrorExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл &apos;{0}&apos; не найден..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon icoApp {
            get {
                object obj = ResourceManager.GetObject("icoApp", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблон rdp-файла &apos;{0}&apos; содержит недопустимый атрибут &apos;{1}&apos;..
        /// </summary>
        internal static string RdpFileAttributeError {
            get {
                return ResourceManager.GetString("RdpFileAttributeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблон rdp-файла &apos;{0}&apos; пуст..
        /// </summary>
        internal static string RdpFileEmpty {
            get {
                return ResourceManager.GetString("RdpFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл настроек &apos;{0}&apos; не найден..
        /// </summary>
        internal static string SettingsFileNotFound {
            get {
                return ResourceManager.GetString("SettingsFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задан параметр &apos;{0}&apos;  в файле настроек &apos;{1}&apos;..
        /// </summary>
        internal static string SettingsParameterIsNull {
            get {
                return ResourceManager.GetString("SettingsParameterIsNull", resourceCulture);
            }
        }
    }
}
