//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wmsMLC.General.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DeveloperExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeveloperExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wmsMLC.General.Resources.DeveloperExceptionResources", typeof(DeveloperExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможны ошибки при кэшировании. Параметр типа &apos;{0}&apos; не можеть быть ключем кэша..
        /// </summary>
        public static string BadCacheParameterType {
            get {
                return ResourceManager.GetString("BadCacheParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует первичный ключ..
        /// </summary>
        public static string CantFindPrimaryKey {
            get {
                return ResourceManager.GetString("CantFindPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication exception{0}{1}.
        /// </summary>
        public static string CommunicationExceptionFormat {
            get {
                return ResourceManager.GetString("CommunicationExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибки DAL должны обязательно пробрасываться дальше..
        /// </summary>
        public static string DalErrorMustThrow {
            get {
                return ResourceManager.GetString("DalErrorMustThrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one {0} attribute..
        /// </summary>
        public static string DuplicateAttribute {
            get {
                return ResourceManager.GetString("DuplicateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное использования аттрибута {0}. Может применяться только для {1}..
        /// </summary>
        public static string IncorrectUseOfAttribute {
            get {
                return ResourceManager.GetString("IncorrectUseOfAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoC not configured for {0}..
        /// </summary>
        public static string IoCNotConfiguredFor {
            get {
                return ResourceManager.GetString("IoCNotConfiguredFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can work only with {0} objects yet..
        /// </summary>
        public static string ObjectNotImplementedYet {
            get {
                return ResourceManager.GetString("ObjectNotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операции с множественнымы первичными ключами пока не реализованы..
        /// </summary>
        public static string СompositePrimaryKeysIsNotImplementedYet {
            get {
                return ResourceManager.GetString("СompositePrimaryKeysIsNotImplementedYet", resourceCulture);
            }
        }
    }
}
