//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wmsMLC.General.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wmsMLC.General.Resources.ExceptionResources", typeof(ExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be of type &apos;{0}&apos;.
        /// </summary>
        public static string ArgumentTypeError {
            get {
                return ResourceManager.GetString("ArgumentTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно подключиться к серверу. Перезапустите приложение..
        /// </summary>
        public static string BadRequestException {
            get {
                return ResourceManager.GetString("BadRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t deserialize file: &apos;{0}&apos;.
        /// </summary>
        public static string CantDeserializeFile {
            get {
                return ResourceManager.GetString("CantDeserializeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}CommandText: {2}.
        /// </summary>
        public static string CommandDataError {
            get {
                return ResourceManager.GetString("CommandDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close..
        /// </summary>
        public static string ConnectionErrorClose {
            get {
                return ResourceManager.GetString("ConnectionErrorClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open connection string = &apos;{0}&apos;..
        /// </summary>
        public static string ConnectionErrorOpen {
            get {
                return ResourceManager.GetString("ConnectionErrorOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина: &apos;{0}&apos;.
        /// </summary>
        public static string ErrorReason {
            get {
                return ResourceManager.GetString("ErrorReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _sysErrors.
        /// </summary>
        public static string LogMessageBuilderSysError {
            get {
                return ResourceManager.GetString("LogMessageBuilderSysError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _sysLogMessages.
        /// </summary>
        public static string LogMessageBuilderSysLogMessages {
            get {
                return ResourceManager.GetString("LogMessageBuilderSysLogMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдена сборка &apos;{0}&apos;..
        /// </summary>
        public static string NotAssemblyResolve {
            get {
                return ResourceManager.GetString("NotAssemblyResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Not file in directory].
        /// </summary>
        public static string NotFileInDirectory {
            get {
                return ResourceManager.GetString("NotFileInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IS_NOT_WF_OBJECT..
        /// </summary>
        public static string ObjectIsNotWf {
            get {
                return ResourceManager.GetString("ObjectIsNotWf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OracleParameter expected..
        /// </summary>
        public static string OracleParameterExpected {
            get {
                return ResourceManager.GetString("OracleParameterExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied by default policy..
        /// </summary>
        public static string SecurityAccessDenied {
            get {
                return ResourceManager.GetString("SecurityAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно прав для выполнения операции (&apos;{0}&apos;)..
        /// </summary>
        public static string SecurityInsufficientPermissionsToOperation {
            get {
                return ResourceManager.GetString("SecurityInsufficientPermissionsToOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует связь с сервисом..
        /// </summary>
        public static string ServiceConnectionError {
            get {
                return ResourceManager.GetString("ServiceConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутсвует связь с сервисом..
        /// </summary>
        public static string ServiceUnavailable {
            get {
                return ResourceManager.GetString("ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Истек период ожидания ответа..
        /// </summary>
        public static string TimeoutExceptionMessage {
            get {
                return ResourceManager.GetString("TimeoutExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSMQ timeout expired..
        /// </summary>
        public static string TimeoutExceptionMSMQMessage {
            get {
                return ResourceManager.GetString("TimeoutExceptionMSMQMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибки при работе с транзакциями. Кол-во ссылок &lt; 0..
        /// </summary>
        public static string TransactionError {
            get {
                return ResourceManager.GetString("TransactionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified TransferEncoding is not supported: {0}..
        /// </summary>
        public static string TransferEncodingNotSupported {
            get {
                return ResourceManager.GetString("TransferEncodingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля &apos;{0}{1}&apos; не может быть конвертировано в тип &apos;{2}&apos;..
        /// </summary>
        public static string TypeConversionError {
            get {
                return ResourceManager.GetString("TypeConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная ошибка.
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authenticated..
        /// </summary>
        public static string UserNotAuthenticated {
            get {
                return ResourceManager.GetString("UserNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User signature is not valid..
        /// </summary>
        public static string UserSignatureNotValid {
            get {
                return ResourceManager.GetString("UserSignatureNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр &apos;{0}&apos; входит в коллекцию параметров {1} рз., что превышает допустимое число {2}..
        /// </summary>
        public static string ValidationCountParametersError {
            get {
                return ResourceManager.GetString("ValidationCountParametersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбраны обязательные параметры..
        /// </summary>
        public static string ValidationRequireParametersError {
            get {
                return ResourceManager.GetString("ValidationRequireParametersError", resourceCulture);
            }
        }
    }
}
