//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wmsMLC.General.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wmsMLC.General.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать.
        /// </summary>
        public static string ActionPrint {
            get {
                return ResourceManager.GetString("ActionPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neither the executeMethod nor the canExecuteMethod delegates can be null..
        /// </summary>
        public static string DelegateCommandDelegatesCannotBeNull {
            get {
                return ResourceManager.GetString("DelegateCommandDelegatesCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T for DelegateCommand&amp;lt;T&amp;gt; is not an object nor Nullable..
        /// </summary>
        public static string DelegateCommandInvalidGenericPayloadType {
            get {
                return ResourceManager.GetString("DelegateCommandInvalidGenericPayloadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не сформировано EPS-задание: {0}..
        /// </summary>
        public static string EpsJobCreateError {
            get {
                return ResourceManager.GetString("EpsJobCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сформировано EPS-задание &apos;{0}&apos; отчета &apos;{1}&apos; на принтер &apos;{2}&apos;..
        /// </summary>
        public static string EpsJobCreateOk {
            get {
                return ResourceManager.GetString("EpsJobCreateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось запустить сервис.
        /// </summary>
        public static string FailedToStartService {
            get {
                return ResourceManager.GetString("FailedToStartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для {0} {1}.
        /// </summary>
        public static string FormatForItem {
            get {
                return ResourceManager.GetString("FormatForItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to логический принтер для отчета &apos;{0}&apos; заблокирован.
        /// </summary>
        public static string FormatPrinterLogicalIsLocked {
            get {
                return ResourceManager.GetString("FormatPrinterLogicalIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не найден логический принтер для отчета &apos;{0}&apos;.
        /// </summary>
        public static string FormatPrinterLogicalPrinterNotFound {
            get {
                return ResourceManager.GetString("FormatPrinterLogicalPrinterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to принтер для отчета &apos;{0}&apos; заблокирован.
        /// </summary>
        public static string FormatPrinterPhysicalIsLocked {
            get {
                return ResourceManager.GetString("FormatPrinterPhysicalIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не найден принтер для отчета &apos;{0}&apos;.
        /// </summary>
        public static string FormatPrinterPhysicalPrinterNotFound {
            get {
                return ResourceManager.GetString("FormatPrinterPhysicalPrinterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to конфигурация потока печати для отчета &apos;{0}&apos; заблокирована.
        /// </summary>
        public static string FormatPrintStreamConfigIsLocked {
            get {
                return ResourceManager.GetString("FormatPrintStreamConfigIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в конфигурации потока печати отчет &apos;{0}&apos; не определен.
        /// </summary>
        public static string FormatPrintStreamConfigNotFound {
            get {
                return ResourceManager.GetString("FormatPrintStreamConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в конфигурации потока печати для отчета &apos;{0}&apos; не определен принтер.
        /// </summary>
        public static string FormatPrintStreamConfigNotLogicalPrinter {
            get {
                return ResourceManager.GetString("FormatPrintStreamConfigNotLogicalPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отчет &apos;{0}&apos; заблокирован.
        /// </summary>
        public static string FormatReportIsLocked {
            get {
                return ResourceManager.GetString("FormatReportIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отчет &apos;{0}&apos; не найден.
        /// </summary>
        public static string FormatReportNotFound {
            get {
                return ResourceManager.GetString("FormatReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблема связи: {0}.
        /// </summary>
        public static string PrefixCommunicationException {
            get {
                return ResourceManager.GetString("PrefixCommunicationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработчику: {0}.
        /// </summary>
        public static string PrefixDeveloperException {
            get {
                return ResourceManager.GetString("PrefixDeveloperException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка настроек: {0}.
        /// </summary>
        public static string PrefixSettingsException {
            get {
                return ResourceManager.GetString("PrefixSettingsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прервано пользователем.
        /// </summary>
        public static string PrefixUserAbortException {
            get {
                return ResourceManager.GetString("PrefixUserAbortException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис запущен....
        /// </summary>
        public static string ServiceIsRunned {
            get {
                return ResourceManager.GetString("ServiceIsRunned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При записи сообщения {0}, возникла ошибка: {1}.
        /// </summary>
        public static string SystemLogWriterTitle {
            get {
                return ResourceManager.GetString("SystemLogWriterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не может быть пустым.
        /// </summary>
        public static string Validation_RequiredDescription {
            get {
                return ResourceManager.GetString("Validation_RequiredDescription", resourceCulture);
            }
        }
    }
}
