//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wmsMLC.General.PL.WPF.Components.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wmsMLC.General.PL.WPF.Components.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Error_48x48 {
            get {
                object obj = ResourceManager.GetObject("Error_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина: {0}.
        /// </summary>
        public static string ErrorReason {
            get {
                return ResourceManager.GetString("ErrorReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Конец трассировки внутреннего стека исключений ---.
        /// </summary>
        public static string ErrorStackTrace {
            get {
                return ResourceManager.GetString("ErrorStackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Непредвиденная ошибка.
        /// </summary>
        public static string ErrorUnexpected {
            get {
                return ResourceManager.GetString("ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть строку автофильтра.
        /// </summary>
        public static string HideAutoFilterMenuItemContent {
            get {
                return ResourceManager.GetString("HideAutoFilterMenuItemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть панель итогов.
        /// </summary>
        public static string HideTotalSummaryContent {
            get {
                return ResourceManager.GetString("HideTotalSummaryContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Information_48x48 {
            get {
                object obj = ResourceManager.GetObject("Information_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строк: {0}.
        /// </summary>
        public static string ListBoxTotalRowsDisplayFormat {
            get {
                return ResourceManager.GetString("ListBoxTotalRowsDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал {0}.
        /// </summary>
        public static string ObjectListViewModelBasePanelCaptionFormatDefault {
            get {
                return ResourceManager.GetString("ObjectListViewModelBasePanelCaptionFormatDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Question_48x48 {
            get {
                object obj = ResourceManager.GetObject("Question_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать строку автофильтра.
        /// </summary>
        public static string ShowAutoFilterMenuItemContent {
            get {
                return ResourceManager.GetString("ShowAutoFilterMenuItemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать панель итогов.
        /// </summary>
        public static string ShowTotalSummaryContent {
            get {
                return ResourceManager.GetString("ShowTotalSummaryContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системная ошибка..
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строк: {0}{2} {1}    {3}.
        /// </summary>
        public static string TotalRowItemDisplayFormat {
            get {
                return ResourceManager.GetString("TotalRowItemDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Отобрано: {0}).
        /// </summary>
        public static string TotalRowItemVisibleRowDisplayFormat {
            get {
                return ResourceManager.GetString("TotalRowItemVisibleRowDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, подождите....
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Warning_48x48 {
            get {
                object obj = ResourceManager.GetObject("Warning_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
