//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wmsMLC.DCL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DeveloperExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeveloperExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wmsMLC.DCL.Resources.DeveloperExceptionResources", typeof(DeveloperExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t block items..
        /// </summary>
        public static string CantBlockItems {
            get {
                return ResourceManager.GetString("CantBlockItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create shell..
        /// </summary>
        public static string CantCreateShell {
            get {
                return ResourceManager.GetString("CantCreateShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create viewmodel for command {0}..
        /// </summary>
        public static string CantCreateViewmodelForCommand {
            get {
                return ResourceManager.GetString("CantCreateViewmodelForCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find item for close..
        /// </summary>
        public static string CantFindItemForClose {
            get {
                return ResourceManager.GetString("CantFindItemForClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find view for view model {0}..
        /// </summary>
        public static string CantFindViewForViewModel {
            get {
                return ResourceManager.GetString("CantFindViewForViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get AreaBlocking..
        /// </summary>
        public static string CantGetArea2Blocking {
            get {
                return ResourceManager.GetString("CantGetArea2Blocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get default path. Company not found..
        /// </summary>
        public static string CantGetDefaultPathCompanyNotFound {
            get {
                return ResourceManager.GetString("CantGetDefaultPathCompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get default path. Product not found..
        /// </summary>
        public static string CantGetDefaultPathProductNotFound {
            get {
                return ResourceManager.GetString("CantGetDefaultPathProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get index from panel caption &apos;{0}&apos;..
        /// </summary>
        public static string CantGetIndexFromPanel {
            get {
                return ResourceManager.GetString("CantGetIndexFromPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get items..
        /// </summary>
        public static string CantGetItems {
            get {
                return ResourceManager.GetString("CantGetItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get TE2Blocking..
        /// </summary>
        public static string CantGetTE2Blocking {
            get {
                return ResourceManager.GetString("CantGetTE2Blocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t insert items..
        /// </summary>
        public static string CantInsertItems {
            get {
                return ResourceManager.GetString("CantInsertItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t operate with viewmodel..
        /// </summary>
        public static string CantOperateWithViewmodel {
            get {
                return ResourceManager.GetString("CantOperateWithViewmodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t receive items..
        /// </summary>
        public static string CantReceiveItems {
            get {
                return ResourceManager.GetString("CantReceiveItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t reject changes in non editable object..
        /// </summary>
        public static string CantRejectChangesInNonEditableObject {
            get {
                return ResourceManager.GetString("CantRejectChangesInNonEditableObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда не должна была вызваться..
        /// </summary>
        public static string CommandCanEditError {
            get {
                return ResourceManager.GetString("CommandCanEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command {0} is not registered..
        /// </summary>
        public static string CommandIsNotRegistered {
            get {
                return ResourceManager.GetString("CommandIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t have field Name..
        /// </summary>
        public static string DoesntHaveFieldName {
            get {
                return ResourceManager.GetString("DoesntHaveFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region can add only IView..
        /// </summary>
        public static string RegionCanAddOnlyIView {
            get {
                return ResourceManager.GetString("RegionCanAddOnlyIView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source must implement IIsNew..
        /// </summary>
        public static string SourceMustImplementIIsNew {
            get {
                return ResourceManager.GetString("SourceMustImplementIIsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown dialog result..
        /// </summary>
        public static string UnknownDialogResult {
            get {
                return ResourceManager.GetString("UnknownDialogResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown SettingDisplay={0}..
        /// </summary>
        public static string UnknownSettingDisplay {
            get {
                return ResourceManager.GetString("UnknownSettingDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдена группа работы..
        /// </summary>
        public static string WorkGropUndefined {
            get {
                return ResourceManager.GetString("WorkGropUndefined", resourceCulture);
            }
        }
    }
}
