//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wmsMLC.DCL.Configurator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wmsMLC.DCL.Configurator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Атрибут.
        /// </summary>
        internal static string ColumnHeaderAttribute {
            get {
                return ResourceManager.GetString("ColumnHeaderAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сущность.
        /// </summary>
        internal static string ColumnHeaderEntity {
            get {
                return ResourceManager.GetString("ColumnHeaderEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Методы операции &apos;{0}&apos;.
        /// </summary>
        internal static string ColumnHeaderMethodDescription {
            get {
                return ResourceManager.GetString("ColumnHeaderMethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер товара.
        /// </summary>
        internal static string ColumnHeaderPm {
            get {
                return ResourceManager.GetString("ColumnHeaderPm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка PM.
        /// </summary>
        internal static string ConfiguratorPanelCaption {
            get {
                return ResourceManager.GetString("ConfiguratorPanelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод.
        /// </summary>
        internal static string LabelCaptionMethod {
            get {
                return ResourceManager.GetString("LabelCaptionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Методы.
        /// </summary>
        internal static string LabelCaptionMethods {
            get {
                return ResourceManager.GetString("LabelCaptionMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция.
        /// </summary>
        internal static string LabelCaptionOperation {
            get {
                return ResourceManager.GetString("LabelCaptionOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маска.
        /// </summary>
        internal static string LabelCaptionPmConfigByInputMask {
            get {
                return ResourceManager.GetString("LabelCaptionPmConfigByInputMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Массовый ввод.
        /// </summary>
        internal static string LabelCaptionPmConfigByInputMass {
            get {
                return ResourceManager.GetString("LabelCaptionPmConfigByInputMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По товару.
        /// </summary>
        internal static string LabelCaptionPmConfigByProduct {
            get {
                return ResourceManager.GetString("LabelCaptionPmConfigByProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка метода.
        /// </summary>
        internal static string MethodDetail {
            get {
                return ResourceManager.GetString("MethodDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка.
        /// </summary>
        internal static string PmMethodConfigured {
            get {
                return ResourceManager.GetString("PmMethodConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недоступно.
        /// </summary>
        internal static string PmMethodIsUnavailable {
            get {
                return ResourceManager.GetString("PmMethodIsUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недоступно. Выбраны запрещенные методы для данной операции..
        /// </summary>
        internal static string PmMethodIsUnavailableButExists {
            get {
                return ResourceManager.GetString("PmMethodIsUnavailableButExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибки валидации:{0}{1}.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
    }
}
