//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wmsMLC.RCL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wmsMLC.RCL.Resources.ExceptionResources", typeof(ExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t send e-mail ({0})..
        /// </summary>
        public static string CantSendEmail {
            get {
                return ResourceManager.GetString("CantSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибки при создании контекстного меню..
        /// </summary>
        public static string ContextMenuError {
            get {
                return ResourceManager.GetString("ContextMenuError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибки при создании задания (ий) на печать..
        /// </summary>
        public static string EpsCreateTaskError {
            get {
                return ResourceManager.GetString("EpsCreateTaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибки при открытии объекта(ов)..
        /// </summary>
        public static string ItemCantCreate {
            get {
                return ResourceManager.GetString("ItemCantCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект не удален..
        /// </summary>
        public static string ItemCantDelete {
            get {
                return ResourceManager.GetString("ItemCantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект не изменен..
        /// </summary>
        public static string ItemCantEdit {
            get {
                return ResourceManager.GetString("ItemCantEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибки получения данных при применении фильтра..
        /// </summary>
        public static string ItemCantFilter {
            get {
                return ResourceManager.GetString("ItemCantFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект не добавлен..
        /// </summary>
        public static string ItemCantInsert {
            get {
                return ResourceManager.GetString("ItemCantInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибки получения данных при обновлении..
        /// </summary>
        public static string ItemCantRefresh {
            get {
                return ResourceManager.GetString("ItemCantRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка отмены изменений..
        /// </summary>
        public static string ItemCantReject {
            get {
                return ResourceManager.GetString("ItemCantReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект не сохранен..
        /// </summary>
        public static string ItemCantSave {
            get {
                return ResourceManager.GetString("ItemCantSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибки при удалении объекта(ов)..
        /// </summary>
        public static string ItemsCantDelete {
            get {
                return ResourceManager.GetString("ItemsCantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target must be a boolean..
        /// </summary>
        public static string TargetMustBeBool {
            get {
                return ResourceManager.GetString("TargetMustBeBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target must be a visibility,.
        /// </summary>
        public static string TargetMustBeVisibility {
            get {
                return ResourceManager.GetString("TargetMustBeVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибки обновления меню..
        /// </summary>
        public static string TileMenuRefreshError {
            get {
                return ResourceManager.GetString("TileMenuRefreshError", resourceCulture);
            }
        }
    }
}
