//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wmsMLC.RCL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wmsMLC.RCL.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        public static string AboutProgram {
            get {
                return ResourceManager.GetString("AboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрирование.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все ЗНТ.
        /// </summary>
        public static string AllTask {
            get {
                return ResourceManager.GetString("AllTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышено допустимое количество попыток ввода.{0}Приложение будет закрыто..
        /// </summary>
        public static string ApplicationWillBeShutdown {
            get {
                return ResourceManager.GetString("ApplicationWillBeShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка аутентификации.
        /// </summary>
        public static string AuthenticationError {
            get {
                return ResourceManager.GetString("AuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно завершить сеанс. Необходимо закрыть все вкладки..
        /// </summary>
        public static string CantCloseSessionError {
            get {
                return ResourceManager.GetString("CantCloseSessionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить кеш.
        /// </summary>
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутсвует связь с сервисом..
        /// </summary>
        public static string CommunicationError {
            get {
                return ResourceManager.GetString("CommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить объект?.
        /// </summary>
        public static string ConfirmationDeleteObject {
            get {
                return ResourceManager.GetString("ConfirmationDeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись изменена. Обновление приведет к потере несохраненных данных. Продолжить?.
        /// </summary>
        public static string ConfirmationSaveDataOnRefresh {
            get {
                return ResourceManager.GetString("ConfirmationSaveDataOnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имеются несохраненные данные. Сохранить?.
        /// </summary>
        public static string ConfirmationUnsavedData {
            get {
                return ResourceManager.GetString("ConfirmationUnsavedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите выйти из приложения?{0}{1}.
        /// </summary>
        public static string ConfirmExit {
            get {
                return ResourceManager.GetString("ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter - ДА{0}Esc - НЕТ.
        /// </summary>
        public static string ConfirmKeyHelp {
            get {
                return ResourceManager.GetString("ConfirmKeyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBUG.
        /// </summary>
        public static string DEBUG {
            get {
                return ResourceManager.GetString("DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка не определена..
        /// </summary>
        public static string EmptyError {
            get {
                return ResourceManager.GetString("EmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение запущено. Желаем Вам приятной работы{0}{0}Команда разработчиков wmsMLC.
        /// </summary>
        public static string EnjoyYourWork {
            get {
                return ResourceManager.GetString("EnjoyYourWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение невозможно.
        /// </summary>
        public static string ErrorSave {
            get {
                return ResourceManager.GetString("ErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная ошибка.
        /// </summary>
        public static string ErrorUndefined {
            get {
                return ResourceManager.GetString("ErrorUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Добавлено объектов: {0}&quot;.
        /// </summary>
        public static string FormulaSaveItemsTemplateMessage {
            get {
                return ResourceManager.GetString("FormulaSaveItemsTemplateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приемка.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инфо.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По месту.
        /// </summary>
        public static string InfoOnPlace {
            get {
                return ResourceManager.GetString("InfoOnPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По ТЕ.
        /// </summary>
        public static string InfoOnTe {
            get {
                return ResourceManager.GetString("InfoOnTe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество входящих сообщений: {0}.
        /// </summary>
        public static string InputMessageCount {
            get {
                return ResourceManager.GetString("InputMessageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инв-я.
        /// </summary>
        public static string INV {
            get {
                return ResourceManager.GetString("INV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин:.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBUG MODE.
        /// </summary>
        public static string LogInfoDebugMode {
            get {
                return ResourceManager.GetString("LogInfoDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =================.
        /// </summary>
        public static string LogInfoHeader01 {
            get {
                return ResourceManager.GetString("LogInfoHeader01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----------------.
        /// </summary>
        public static string LogInfoHeader02 {
            get {
                return ResourceManager.GetString("LogInfoHeader02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start application.
        /// </summary>
        public static string LogInfoStartApp {
            get {
                return ResourceManager.GetString("LogInfoStartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop application.
        /// </summary>
        public static string LogInfoStopApp {
            get {
                return ResourceManager.GetString("LogInfoStopApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Ваш логин....
        /// </summary>
        public static string LoginNullText {
            get {
                return ResourceManager.GetString("LoginNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новое значение.
        /// </summary>
        public static string LookupAddButtonTooltip {
            get {
                return ResourceManager.GetString("LookupAddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string MainMenuBackCaption {
            get {
                return ResourceManager.GetString("MainMenuBackCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход из приложения.
        /// </summary>
        public static string MainMenuExitCaption {
            get {
                return ResourceManager.GetString("MainMenuExitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string MainMenuSubPrintCaption {
            get {
                return ResourceManager.GetString("MainMenuSubPrintCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТЕ не имеет назначенных отчетов..
        /// </summary>
        public static string MainMenuTeNoReportCaption {
            get {
                return ResourceManager.GetString("MainMenuTeNoReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транспортные задания {0}.
        /// </summary>
        public static string MainMenuTransportTaskCaption {
            get {
                return ResourceManager.GetString("MainMenuTransportTaskCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подбор.
        /// </summary>
        public static string MainTileMenuPickingLisHeader {
            get {
                return ResourceManager.GetString("MainTileMenuPickingLisHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string MainTileMenuRefreshHeader {
            get {
                return ResourceManager.GetString("MainTileMenuRefreshHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗНТ.
        /// </summary>
        public static string MainTileMenuTransportTaskHeader {
            get {
                return ResourceManager.GetString("MainTileMenuTransportTaskHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти в систему.
        /// </summary>
        public static string MainViewModel_Login {
            get {
                return ResourceManager.GetString("MainViewModel_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти из системы [{0}].
        /// </summary>
        public static string MainViewModel_Logoff_Template {
            get {
                return ResourceManager.GetString("MainViewModel_Logoff_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меню.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic solutions since 1990.
        /// </summary>
        public static string MlcDescription {
            get {
                return ResourceManager.GetString("MlcDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перем-ие.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдача.
        /// </summary>
        public static string Out {
            get {
                return ResourceManager.GetString("Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Ваш пароль....
        /// </summary>
        public static string PasswordNullText {
            get {
                return ResourceManager.GetString("PasswordNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCL.
        /// </summary>
        public static string RCL {
            get {
                return ResourceManager.GetString("RCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет....
        /// </summary>
        public static string ReportCommand {
            get {
                return ResourceManager.GetString("ReportCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите сотрудника.
        /// </summary>
        public static string SelectWorkerPanelCaption {
            get {
                return ResourceManager.GetString("SelectWorkerPanelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщить.
        /// </summary>
        public static string SendMail {
            get {
                return ResourceManager.GetString("SendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аутентификация.
        /// </summary>
        public static string StateAuthentication {
            get {
                return ResourceManager.GetString("StateAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация модулей.
        /// </summary>
        public static string StateInitModules {
            get {
                return ResourceManager.GetString("StateInitModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется: {0}.
        /// </summary>
        public static string StatePrefix {
            get {
                return ResourceManager.GetString("StatePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск приложения.
        /// </summary>
        public static string StateRun {
            get {
                return ResourceManager.GetString("StateRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск модулей.
        /// </summary>
        public static string StateRunModules {
            get {
                return ResourceManager.GetString("StateRunModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валидация погрузчика.
        /// </summary>
        public static string StateValidateTruck {
            get {
                return ResourceManager.GetString("StateValidateTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валидация работника.
        /// </summary>
        public static string StateValidateWorker {
            get {
                return ResourceManager.GetString("StateValidateWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключение.
        /// </summary>
        public static string SysDbInfoDialogTitle {
            get {
                return ResourceManager.GetString("SysDbInfoDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to БД: {0}{1}Версия: {2}{1}Расположение: {3}.
        /// </summary>
        public static string SysDbInfoMessage {
            get {
                return ResourceManager.GetString("SysDbInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системное сообщение.
        /// </summary>
        public static string SystemMessage {
            get {
                return ResourceManager.GetString("SystemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Истек период ожидания ответа..
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В настройках Вашего терминала &apos;{0}&apos; не определен погрузчик. Приложение будет завершено..
        /// </summary>
        public static string TruckNotValidated {
            get {
                return ResourceManager.GetString("TruckNotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибки при определении кода погрузчика. Приложение будет завершено..
        /// </summary>
        public static string TruckValidatedError {
            get {
                return ResourceManager.GetString("TruckValidatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидаем запуск сервиса....
        /// </summary>
        public static string WaitServiceInit {
            get {
                return ResourceManager.GetString("WaitServiceInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ждите....
        /// </summary>
        public static string WaitShort {
            get {
                return ResourceManager.GetString("WaitShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работа.
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудники.
        /// </summary>
        public static string WorkerList {
            get {
                return ResourceManager.GetString("WorkerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудник не выбран. Выберите сотрудника..
        /// </summary>
        public static string WorkerNotSelect {
            get {
                return ResourceManager.GetString("WorkerNotSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К пользователю &apos;{0}&apos; не привязан ни один работник.  Приложение будет завершено..
        /// </summary>
        public static string WorkerNotValidated {
            get {
                return ResourceManager.GetString("WorkerNotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибки при определении работника.  Приложение будет завершено..
        /// </summary>
        public static string WorkerValidatedError {
            get {
                return ResourceManager.GetString("WorkerValidatedError", resourceCulture);
            }
        }
    }
}
